version: '3'
services:
  db:
    image: mysql:5.7.22
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '4306:3306'
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    env_file: .env.development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 4000:3000
volumes:
  ? node_modules
  ? db_data
